# Generated by Django 5.0.3 on 2024-06-11 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=50)),
                ('inicio', models.DateField(default=django.utils.timezone.now)),
                ('prazo', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
