# Generated by Django 5.0.3 on 2024-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        ('vendedores', '0009_remove_vendedores_produtos_vendidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedores'),
        ),
    ]
