# Generated by Django 5.0.3 on 2024-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa',
            field=models.CharField(max_length=500),
        ),
    ]
