# Generated by Django 5.0.3 on 2024-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefas_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa',
            field=models.TextField(),
        ),
    ]
