# Generated by Django 5.0.3 on 2024-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_tarefas_cor_alter_tarefas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='recorrencia',
            field=models.BooleanField(default=False),
        ),
    ]
