# Generated by Django 5.0.3 on 2024-07-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_tarefas_recorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='recorrencia',
            field=models.CharField(choices=[('1', 'Diária'), ('2', 'Semanal'), ('3', 'Mensal'), ('4', 'Dias alternados')], max_length=50),
        ),
    ]
