# Generated by Django 5.0.3 on 2024-03-13 21:01

import datetime
import django.db.models.deletion
import estoque.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_barras', models.CharField(default=estoque.functions.gerar_ean13, max_length=14, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('estoque_minimo', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('observacoes', models.CharField(blank=True, max_length=500, null=True)),
                ('tamanho', models.CharField(max_length=5)),
                ('fornecedor', models.CharField(default='Sem fornecedor', max_length=200)),
                ('cor', models.CharField(max_length=200)),
                ('custo', models.CharField(max_length=200)),
                ('venda', models.CharField(max_length=100)),
                ('imagem', models.BinaryField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.categoriaestoque')),
                ('marca', models.ForeignKey(default='Sem Marca', on_delete=django.db.models.deletion.CASCADE, to='estoque.marcaestoque')),
            ],
        ),
    ]
