# Generated by Django 5.0.3 on 2024-03-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_cor_alter_estoque_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
