# Generated by Django 5.0.3 on 2024-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='cor',
            field=models.CharField(default='Azul', max_length=200),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.CharField(default='Sem descrição', max_length=200),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='estoque_minimo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tamanho',
            field=models.CharField(default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
