# Generated by Django 5.0.3 on 2024-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_estoque_cor_alter_estoque_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='cor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
