# Generated by Django 5.0.3 on 2024-03-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_estoque_cor_alter_estoque_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.marcaestoque'),
        ),
    ]
