# Generated by Django 5.0.3 on 2024-08-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_estoque_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='imagem',
        ),
    ]
