# Generated by Django 5.0.3 on 2024-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('messagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
            ],
        ),
    ]
