# Generated by Django 5.0.3 on 2024-07-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messagem',
            new_name='mensagem',
        ),
    ]
