# Generated by Django 5.0.3 on 2024-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
