# Generated by Django 5.0.3 on 2024-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
    ]
