# Generated by Django 5.0.3 on 2024-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_vendedores_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='ferias',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
