# Generated by Django 5.0.3 on 2024-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_alter_vendedores_ferias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
