# Generated by Django 5.0.3 on 2024-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0004_vendedores_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='produtos_vendidos',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
