# Generated by Django 5.0.3 on 2024-05-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0006_alter_vendedores_produtos_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='foto',
            field=models.ImageField(default='https://xsgames.co/randomusers/avatar.php?g=pixel', upload_to=''),
        ),
    ]
