# Generated by Django 5.0.3 on 2024-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0007_vendedores_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedores',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
