# Generated by Django 5.0.3 on 2024-05-23 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0008_alter_vendedores_options_alter_vendedores_comissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedores',
            name='produtos_vendidos',
        ),
        migrations.AddField(
            model_name='vendedores',
            name='porcentegem_comissao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='vendedores',
            name='total_em_vendas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='ferias',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EventoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendedores.vendedores')),
            ],
            options={
                'verbose_name': 'Evento de Venda',
                'verbose_name_plural': 'Eventos de Vendas',
            },
        ),
    ]
