# Generated by Django 5.0.3 on 2024-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0009_remove_vendedores_produtos_vendidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventovenda',
            name='produto',
            field=models.CharField(max_length=500),
        ),
    ]
