# Generated by Django 5.0.3 on 2024-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorrencia', models.BooleanField()),
                ('status', models.CharField(choices=[('C', 'CONCLUÍDO'), ('P', 'PENDENTE')], max_length=50)),
            ],
        ),
    ]
