# Generated by Django 5.0.3 on 2024-07-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidas',
            name='recorrencia',
        ),
        migrations.RemoveField(
            model_name='saidas',
            name='status',
        ),
    ]
