# Generated by Django 5.0.3 on 2024-05-03 16:54

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_alter_eventos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('saida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('saldo', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('valor_inicial'), '-', models.F('saida')), output_field=models.DecimalField(decimal_places=2, max_digits=6))),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(default='', max_length=1300)),
                ('desconto', models.IntegerField(default=0)),
                ('forma_pagamento', models.CharField(choices=[('CARTAO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX')], max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes')),
            ],
        ),
    ]
