# Generated by Django 5.0.3 on 2024-04-19 18:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_alter_eventos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(default='', max_length=1300)),
                ('forma_pagamento', models.CharField(choices=[('CARTAO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX')], max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes')),
            ],
        ),
    ]
