# Generated by Django 5.0.3 on 2024-05-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='saldo',
        ),
    ]
