# Generated by Django 5.0.3 on 2024-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='desconto',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
