# Generated by Django 5.0.3 on 2024-06-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_estoque_imagem'),
        ('vendas', '0004_vendas_vendedor_alter_vendas_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_troca', models.DateField(auto_now_add=True)),
                ('valor_diferenca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_novo', to='estoque.estoque')),
                ('produto_trocado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_trocado', to='estoque.estoque')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
            ],
        ),
    ]
