# Generated by Django 5.0.3 on 2024-04-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_url_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='Não Possui@email.com', max_length=50),
        ),
    ]
