# Generated by Django 5.0.3 on 2024-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='NPossui@email.com', max_length=50),
        ),
    ]
