# Generated by Django 5.0.3 on 2024-04-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Eventos',
        ),
    ]
