# Generated by Django 5.0.3 on 2024-04-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_evento_eventos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': 'Eventos'},
        ),
    ]
