# Generated by Django 5.0.3 on 2024-05-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_eventos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='url_instagram',
            field=models.TextField(blank=True, null=True),
        ),
    ]
