# Generated by Django 5.0.3 on 2024-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_clientes_url_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='url_instagram',
            field=models.URLField(blank=True, default='https://xsgames.co/randomusers/avatar.php?g=pixel'),
        ),
    ]
